name: 虚無レシピ
description: 虚無シリーズの追加
title: "虚無"
labels:
  - kyomu
# assignees:
#   - ina6ra
body:
  - type: input
    id: vid
    attributes:
      label: URL
      description: 虚無レシピのYoutubeリンク
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: 投稿日
      description: 虚無レシピの投稿日
    validations:
      required: true
  - type: input
    id: price
    attributes:
      label: 材料費
      description: 虚無レシピの材料費
    validations:
      required: false
