name: 虚無レシピ
description: 虚無シリーズの追加
title: "虚無"
labels:
  - kyomu
body:
  - type: input
    id: vid
    attributes:
      label: URL
      description: 虚無レシピのYoutubeリンク
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: 投稿日
      description: 虚無レシピの投稿日
      placeholder: 2022-06-15
    validations:
      required: true
  - type: input
    id: price
    attributes:
      label: 材料費
      description: 虚無レシピの材料費
      placeholder: 77円
    validations:
      required: false
